# Generated by Django 5.0.2 on 2024-03-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("IngredientHub", "0003_recipe_created_date_recipe_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                choices=[
                    ("eggs, milk and milk products", "Eggs, Milk and Milk products"),
                    ("fats and oils", "Fats and Oils"),
                    ("fruits", "Fruits"),
                    (
                        "grain, nuts and baking products",
                        "Grain, Nuts and Baking products",
                    ),
                    ("herbs and spices", "Herbs and Spices"),
                    ("meat, suasages and fish", "Meat, Sausages and Fish"),
                    ("pasta, rice and pulses", "Pasta, Rice and Pulses"),
                    ("vegetables", "Vegetables"),
                    ("sauces", "Sauces"),
                    ("bead", "Bread"),
                    ("others", "Others"),
                ],
                max_length=100,
            ),
        ),
    ]
