# Generated by Django 5.0.2 on 2024-03-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("IngredientHub", "0005_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                choices=[
                    ("Eggs, Milk, and Milk Products", "Eggs, Milk, and Milk Products"),
                    ("Fats and Oils", "Fats and Oils"),
                    ("Fruits", "Fruits"),
                    (
                        "Grains, Nuts, and Baking Products",
                        "Grains, Nuts, and Baking Products",
                    ),
                    ("Herbs and Spices", "Herbs and Spices"),
                    ("Meats", "Meats"),
                    ("Seafoods", "Seafoods"),
                    ("Pasta, Rice, and Pulses", "Pasta, Rice, and Pulses"),
                    ("Vegetables", "Vegetables"),
                    ("Sauces", "Sauces"),
                    ("Breads", "Breads"),
                    ("Processed Foods", "Processed Foods"),
                    ("Beverages", "Beverages"),
                    ("Alcohol", "Alcohol"),
                    ("Others", "Others"),
                ],
                max_length=100,
            ),
        ),
    ]
