# Generated by Django 5.0.2 on 2024-03-07 16:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("IngredientHub", "0009_alter_category_name"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Ingredient",
            new_name="GroceryProduct",
        ),
    ]
