# Generated by Django 5.0.2 on 2024-03-11 02:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("IngredientHub", "0017_alter_recipeingredient_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeingredient",
            name="quantity",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="unit",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
