# Generated by Django 5.0.2 on 2024-03-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("IngredientHub", "0018_alter_recipeingredient_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breakfastlunchdinner",
            name="planned_date",
            field=models.DateField(blank=True, null=True, unique=True),
        ),
    ]
