# Generated by Django 5.0.2 on 2024-03-11 21:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("IngredientHub", "0019_alter_breakfastlunchdinner_planned_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="planned_date",
        ),
    ]
