# Generated by Django 5.0.2 on 2024-03-14 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("IngredientHub", "0020_remove_recipe_planned_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeingredient",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="through_ing",
                to="IngredientHub.groceryproduct",
            ),
        ),
    ]
