# Generated by Django 5.0.2 on 2024-03-15 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("IngredientHub", "0021_alter_recipeingredient_ingredient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeingredient",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="through_rec",
                to="IngredientHub.recipe",
            ),
        ),
    ]
